version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  api-build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run script
          command: python src/app.py
      - run: mkdir code
      - run: cp -R ./* code
      - persist_to_workspace:
          root: code
          paths:
              - '*'
  api-test:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      # - checkout
      - attach_workspace:
          at: ~/repo/workspace
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  backend-build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run script
          command: python src/app.py
  backend-test:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - run: echo Deploy build
workflows:
  version: 3
  build-test-deploy:
    jobs:
      - api-build
      - api-test:
          requires:
            - api-build
      - backend-build
      - backend-test:
          requires:
            - backend-build
      - deploy:
          requires:
            - api-test
            - backend-test
