version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    working_directory: /cfm
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run docker compose
          command: |
            docker-compose up -d
            # docker-compose run cfm python backend/worker/app.py
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag cfm_worker $DOCKER_HUB_USER_ID/cfm_worker:$CIRCLE_SHA1
            docker tag cfm_worker $DOCKER_HUB_USER_ID/cfm_worker:latest
            docker push $DOCKER_HUB_USER_ID/cfm_worker:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/cfm_worker:latest
workflows:
  version: 2
  build:
    jobs:
      - build
