version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL # https://284541392707.dkr.ecr.us-east-2.amazonaws.com
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./backend/worker
          region: AWS_REGION
          repo: circleci-ecr-orb-demo-worker
          skip-when-tags-exist: false
          tag: "latest"
