version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run script
          command: python src/app.py
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - run:
          name: Run tests
          command: pytest
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - run: echo 'Deploy build'
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
