version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run script
          command: python src/app.py
    test:
      steps:
        - run:
            name: Run tests
            command: pytest
    deploy:
      steps:
        - run: echo 'Deploy build'
workflows:
  sample:
    jobs:
      - build
      - test
          requires:
            - build
      - deploy
          requires:
            - test
