version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  api-build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run script
          command: python src/app.py
      # - run: mkdir project_code
      # - run: cp -R ./* project_code
      # - persist_to_workspace:
      #     root: project_code
      #     paths:
      #         - '*'
  api-test:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/repo/workspace
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  backend-build:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run script
          command: python src/app.py
  backend-test:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - run: echo Deploy build
  dev-test:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/cfm
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - api-build
      - api-test:
          requires:
            - api-build
      - backend-build
      - backend-test:
          requires:
            - backend-build
      - dev-test:
          requires:
            - api-test
            - backend-test
          filters:
            branch:
              ignore:
                - main
      - deploy:
          requires:
            - api-test
            - backend-test
          filters:
            branches:
              only:
                - main
